#!/bin/sh
#
# /etc/init.d/redsmin
# Subsystem file for "redsmin" server
#
# chkconfig: 2345 95 05
# description: redsmin server daemon
#
# processname: redsmin
# pidfile: /etc/run/redsmin.pid
# config: /etc/redmins/redsmin.json

set CONFIG_FILE=/etc/redsmin/redsmin.json
EXEC="/usr/bin/redsmin &"
PIDFILE=/var/run/redsmin.pid

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redsmin proxy server..."
		$EXEC
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                killall redsmin
		rm -f $PIDFILE
                echo "Redsmin stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
